sepal_ui/sepalwidgets.py, sepal_ui/styles/styles.py
The pull request consider some changes:
1. Created `styles.py` file:
- Including some css styles to prevent ipyleaflet maps overlap with sepal widgets, by changing z-indexes.
- Compiled dictionaries to merge styles used in sepal apps, so we can add or remove according to our needs.
2. Second FileInput draft based on previous existing:
- Improved speed in loading elements
- Added progress bar at the top of the menu, so the user knows the menu is working.
- Added size to every loaded element without affecting the speed of loading (we could think on make this optional), it's useful to at least warning to the user when is trying to open a huge file.
- Sorted elements. First displaying folders and then files, not mixing them.
- Added the ability to go back to the parent folder with the first …
=> Styles in one file - filechooser

docs/source/tutorials/send-to-sepal.rst, requirements.txt, sepal_ui/bin/module_deploy, setup.py
Fix #228 
In the next SEPAL release we will be given the oportunity to add requirements file for our module. I don't want to spend my entire time to edit requirements.txt file for others so I created this script that is retrieving the used libs from the folder and then edit automatically a requirements.txt file. 
It is based on the default requirements.txt file that is available in sepal_ui_template: https://github.com/12rambau/sepal_ui_template/blob/master/requirements.txt
Some libs are known troubleshoutings (GDAL, PROJ, earthengine) and are handle by the script. Any new strange behaviour should be added in this method: https://github.com/12rambau/sepal_ui/blob/9b1387c1727e35ba4891f4e361ee531adedf35bd/sepal_ui/bin/module_deploy#L64
=> add a new bin file to deal with module requirements

sepal_ui/scripts/utils.py, sepal_ui/sepalwidgets/inputs.py
In my last commit I removed the type for two reasons (is should have ammed the last one, sorry):
- its a reserved python keyword, and also was causing problems with the widget.
- there is no need to have it if we are storing all in asset_info
=> fix: remove type and feat: introducing switch decorator

docs/source/widgets/clip.rst, docs/source/widgets/index.rst, sepal_ui/sepalwidgets/sepalwidget.py, tests/test_Clip.py, tests/test_CopyToClip.py
It finally works, the RPC way of calling javascripts methods directly from python will be super useful. We needed to wait for voila XX.12 to make javascript executable from dashboards (that was already working from Jupyter notebook and lab). 
The javascript command used here (`document.execCommand("copy")`) is not working on every browser.... but as a first step I would like to make it available as it's working on the big 3: 
- chrome
- firefox
- opera
It will need further work to make it compatible with everything (hello IE7) but that's another story. I'll wait for people to complain.
Fix #163
=> feat: Copy to clipboard

setup.py
As some of our build will be blocked when 3.6 will be dropped, I suggest we enforce the python version in setup as suggested [here](https://stackoverflow.com/questions/13924931/setup-py-restrict-the-allowable-version-of-the-python-interpreter). When we'll drop the 3.6 build, the previous version will be retreive automatically by pip if needed
=> build: set a minimal python version

sepal_ui/mapping/mapping.py, sepal_ui/message/en.json, sepal_ui/message/es.json, sepal_ui/message/fr.json, sepal_ui/model/model.py, sepal_ui/sepalwidgets/alert.py, sepal_ui/sepalwidgets/app.py, sepal_ui/sepalwidgets/btn.py, sepal_ui/sepalwidgets/inputs.py, sepal_ui/sepalwidgets/sepalwidget.py, sepal_ui/sepalwidgets/tile.py, tests/test_Btn.py
- Avoid the duplication of parameters using an elegant and more pythonic method.
- force the values of the one that we don't want user to overwrite (`children` usually) 
- easyer to read 
- faster to execute as it doesn't require updating traits but just a dict
=> refactor: use kwargs pop

sepal_ui/sepalwidgets/btn.py
One of my previous modification lead to a weird behaviour: when you don't set an icon then you have a blank left-padding. As a fix, I simply hide the component when `children` is set to "". 
The idea is to avoid aving an empty `v_icon` member.
=> fix: hide the icon if set to empty

docs/source/widgets/sepal_widget.rst, sepal_ui/sepalwidgets/sepalwidget.py, tests/test_SepalWidget.py
fix #341 
- set the viz member as a bool trait 
- call `hide`or `show`according to the value of `viz` trait 
- make the `toggle_viz` simply toggle the viz value (I think it should be deprecated at some point in the future
the only issue is that when you call `hide` (or `show`) and there is effectivelly a modification, it will be called twice:
1. byt the effective call to `hide`
2. by the callback when the viz value is changed
That is not costing any sensible time but if you have any idea on how to fix it ;-)
=> make the viz member as a trait

docs/source/modules/sepal_ui.mapping.SepalMap.rst, sepal_ui/mapping/mapping.py, tests/conftest.py, tests/test_SepalMap.py, tests/test_gee.py
Fix #278  
Here is an example file to discover the display options: users/bornToBeAlive/imageViZExample
It is embeding all the possible combination of viz params that SEPAL produces. 
to get them all displayed: 
```python
from sepal_ui import mapping as sm
import ee
image = ee.Image("users/bornToBeAlive/imageViZExample")
sm.SepalMap.get_viz_params(image)
```
display this asset in a map using one of the available viz params: 
```python
from sepal_ui import mapping as sm 
import ee
m = sm.SepalMap()
image = ee.Image("users/bornToBeAlive/imageViZExample")
m.addLayer(image, {}, "test", viz_name="NDWI")
m.zoom_ee_object(image.geometry())
m
```
I still cannot manage to deal with inverted bands (in `NDWI harmonics`), if you have any idea be my guest ;-) 
managed inverted and hsv images: …
=> use SEPAL viz params embeded in the Image metadata to display asset

setup.py
- the previous build was not instaling all the packages when coming from pipy
- the previous build was missing cryptography that is imported even if it's never used outside of a test env (thank you flake8)
- I'll publish the fix directly and import it to my local computer to test it. If it doesn't work I can still remove this release from pipy
=> fix: solve the build issue in SEPAL

.flake8, docs/source/conf.py
I wanted to overwrite a method from a specific object. I was scrolling in the doc and I realized that I was unable to really dive into my function if I wanted to remember how it works. 
I simply added an extension to Sphinx and now the classes and functions have a little `[source]` link. click it and you'll see the corresponding code highlighted in the specific doc page. 
I found it useful. let me know what you think.
a demo page with multiple source entries: https://sepal-ui--367.org.readthedocs.build/en/367/modules/sepal_ui.aoi.AoiModel.html#sepal_ui.aoi.AoiModel.set_default
=> docs: expose the code in the doc

sepal_ui/scripts/utils.py, sepal_ui/sepalwidgets/btn.py, tests/test_DownloadBtn.py, tests/test_utils.py
The SEPAL framework have changed and the entrypoint to file is no longer `/api/files/download?path=`. Instead of relying on SEPAL I tried to use the Jupyter entrypoint (that is always active as the apps are running through Jupyter notebook). 
i.e. I'm now using `https://sepal.io/api/sandbox/jupyter/files`and add 1 extra `download` attribute to the btn.
=> DownloadBtn links

sepal_ui/aoi/aoi_model.py
Fix #391
The file needs to be downloaded anyway as `Geopandas` does not read `StringIO` or `ByteIO` objects. Instead of pointing to the "tmp" folder, I decided to use the `tempfile` Python lib. It creates the tmp directory in (and only in) the `with` statement. This lib being compatible with every OS, it will be more robust than the previous implementation.
=> fix: don't use the named 'tmp' directory

sepal_ui/aoi/aoi_model.py
=> fix: set the name in the properties of the GEJSON output

docs/source/modules/sepal_ui.sepalwidgets.DatePicker.rst, sepal_ui/sepalwidgets/inputs.py, tests/test_DatePicker.py
Fix #409 Add the missing disabled trait to the Datpicker object so that it can be manipulated as any other input:
```python
picker = sw.DatePicker()
picker.disabled = True
picker
```
=> Datepicker disabled trait 

docs/source/modules/sepal_ui.mapping.FullScreenControl.rst, docs/source/modules/sepal_ui.mapping.SepalMap.rst, docs/source/modules/sepal_ui.mapping.rst, sepal_ui/frontend/styles.py, sepal_ui/mapping/__init__.py, sepal_ui/mapping/fullscreen_control.py, tests/test_FullScreenControl.py
create a custom `FullscreenControl`to solve the issue raised in https://github.com/widgetti/ipyvuetify/issues/141. 
This is still a WIP but the results are already promising. I still need to add documentation and tests but that is worth testing on someone else's side. I think some improvement is required on the JS script as it gives funny results in jupyterlab an jupyternotebook at the moment.
Here is an example code for testing :  
```python
from sepal_ui import mapping as sm
from sepal_ui import sepalwidgets as sw
import ipyvuetify as v
from ipyleaflet import WidgetControl
map_=sm.SepalMap(center=[4,-74], zoom=5)
map_.add_control(sm.FullScreenControl(position="topleft"))
dropdown = sw.Select(label="titi", items=["toto",2,3,4,5,], v_model=None)
widget_control = …
```
=> feat: new fullscreen widget

docs/source/modules/sepal_ui.sepalwidgets.DatePicker.rst, sepal_ui/sepalwidgets/inputs.py, tests/test_DatePicker.py
Fix #417 
I think that this function is intended for developers as it's a programmatically triggered change so I didn't put much effort into error catching.
- the `v_model` can be set on object build
```python
d = sw.DatePicker(v_model="2022-03-14")
d
```
- the `v_model` can be changed on the fly 
```python
d = sw.DatePicker()
d.v_model = "2022-03-14"
d
```
- There is error catching on manual set so that we throw an error when a badly shaped str ins used as v_model
```python 
d = sw.DatePicker()
d.v_model = "2022-50-12"
d
```
=> change the value of the datepicker y changing its v_model

docs/source/modules/sepal_ui.sepalwidgets.DrawerItem.rst, sepal_ui/sepalwidgets/app.py, tests/test_DrawerItem.py
- Aims to close #415
- The way to interact with the drawer is by passing a model and a trait, the drawer will be listening the model trait and will add/remove a red badge accordingly. 
Let me know what do you think!
=> Drawer branch notification

sepal_ui/bin/module_factory, sepal_ui/bin/module_venv
Some minor change to bin commands: 
- the `module_factory`command was relying on a predifined set of languages. to improve robustness, we simply guess the available one. If the key is not there it will be automatically added anyway. same for the doc files. 
-use "set-url" instead of "add" to rewire the git repository. add cannot be used in the new git CLI release when origin already exist 
- use the name of the repository in `module_venv` to prevent funny behaviour when the repo has "." in the name. 
previously runnning it in "se.plan" was crating a "module-venv/se" venv. now it's nicely called "module-venv/se.plan"
=> improve factory and venv command

sepal_ui/bin/activate_venv, setup.py
This command script is intended to make easier the search and activation process of the virtual envs in the platform.
Basically, it will look at the installed venvs in both usr and local module-venvs, and you can choose which one you want to activate.
what do you think? I found a little bit different way to activate the ven but it is working, do you mind taking a review?
=> Command script to activate virtual envs

.github/workflows/unit.yml, .pre-commit-config.yaml, sepal_ui/mapping/mapping.py, sepal_ui/scripts/utils.py, setup.py, tests/test_utils.py
=> fix: unproject images in add_raster

sepal_ui/mapping/fullscreen_control.py, tests/test_FullScreenControl.py
just changing to [arrows expand icon](https://fontawesome.com/v4/icon/arrows-alt)
=> style: change to arrows expand icon, aimd to close #421

docs/source/_static/css/custom.css, setup.py
https://sepal-ui--446.org.readthedocs.build/en/446/
implementing the dark theme I developed for the pydata-sphinx-theme in https://github.com/pydata/pydata-sphinx-theme/pull/540. The idea will be to us it as well in the SEPAL doc.
=> build: use the master version of the doc template

docs/source/modules/sepal_ui.sepalwidgets.SepalWidget.rst, sepal_ui/sepalwidgets/__init__.py, sepal_ui/sepalwidgets/sepalwidget.py, tests/test_SepalWidget.py
In relation to https://github.com/12rambau/sepal_ui/issues/443.
- Rename SepalWidget overwrote Vuetify Classes
- Two new methods created `set_children` and `get_children`:
- I've only included `first` and `last` as available positions when setting new children, do you think is enough? or should we use the indexes instead?
- Tests
- Docs
=> Sepalwidget

docs/source/modules/sepal_ui.translator.Translator.rst, sepal_ui/translator/translator.py, tests/test_Translator.py
=> fix: remove empty string from the translation dict

.github/workflows/release.yml
To have the wheel file available on pipy (useful for jupyterlite and faster way of installing the lib in general) 
#470
=> build: build archive and wheel when publishing

docs/source/modules/sepal_ui.mapping.SepalMap.rst, sepal_ui/mapping/fullscreen_control.py, sepal_ui/mapping/sepal_map.py, sepal_ui/scripts/utils.py, tests/test_FullScreenControl.py, tests/test_SepalMap.py
Fix #479 
I set an automatic 6 letters `_id` to the maps. The `_id` is set as the class of the higher level DOM element of the widget.
I needed to add the `m` parameter to the `FullscreenControl` to let him access this value. 
I then slightly modified the JS template using a querySelector (css classic selection) to select the first map with the same class id. 
- As JS is using "{" I was unabled to use f-string or format (cannot escape this charater in any ways). As a last resort I used `%s` a,d it seems to work.
- I decided not to let the developer name the id as nobody will should use this variable outside of JS.
- When the kernel starts a seed is automatically chosen for the "random" module so it's impossible that 2 maps get the same ID. 
copy paste the following code in a voila …
=> make sure the Fullscreen btn widden the appropriate map

docs/source/modules/sepal_ui.mapping.SepalMap.rst, sepal_ui/mapping/sepal_map.py, tests/test_SepalMap.py
attempt to fix #480 
- `zoom_ee_object` now behaves exactly like `CenterObject` as it's accepting `Image`, `Feature` etc...)
- `zoom_raster` allows zooming on a specific raster layer. the layer need to be added to the map first and the layer object in now an output of the `add_raster` method.
- small refactoring of the zoom methods
=> improve zoom management

sepal_ui/frontend/styles.py, sepal_ui/sepalwidgets/alert.py, setup.py, tests/test_Alert.py
This PR aims to introduce the tqdm alert progress bar referenced by the (quite old)  #294 issue. 
- Even though it's doing what's expected, I can't manage to let the `tqdm` container `HBox` inherit the ipyvuetify styles, causing the text within the progress bar to be totally different. @12rambau would you like to give a check?
- In relation to the time, it does totally faster than the previous implementation.
- I've marked it as draft until we can manage the styles, and then I'll proceed with documentation and styles.
```Python
import sepal_ui.sepalwidgets as sw
import urllib
from pathlib import Path
alert = sw.Alert().show()
url = 'https://firms.modaps.eosdis.nasa.gov/data/country/zips/modis_2000_all_countries.zip'
display(alert)
progress = 0
def update_progress(b, bsize, tsize): …
```
=> feat: introduce tqdm progress bar. related with #294

docs/source/modules/sepal_ui.aoi.AoiView.rst, docs/source/modules/sepal_ui.mapping.DrawControl.rst, sepal_ui/aoi/aoi_tile.py, sepal_ui/aoi/aoi_view.py, sepal_ui/mapping/draw_control.py, sepal_ui/mapping/sepal_map.py, sepal_ui/sepalwidgets/inputs.py, setup.py, tests/test_AoiView.py, tests/test_DrawControl.py, tests/test_LoadTableField.py
Fix #386 
- add a to_json method to the Draw_control. using it you'll get everything drawn on the map without the style as a geo_interface
- also use the previously coded (aoiView) polygonize method to manage circles 
- update to ipyleaflet 0.14.0 (introduction of the DrawControl data trait) 
- small correction of the remov_layer method (avoid throwing an error when none_ok == True)
- update AoiView to use this DC methods 
- refactor AoiView
```python 
from sepal_ui.mapping import *
m = SepalMap(dc=True)
m
```
Edit the features as much a you want and observe the content from 
```python 
m.dc.data
```
Export it as a usable geo_interface: 
```python
m.dc.to_json()
```
=> Manage edited geometries

sepal_ui/aoi/aoi_view.py, sepal_ui/sepalwidgets/inputs.py
I removed the None test in fileinput in 2.9.0 thinking I was optimizing the code. 
This test is to prevent to reload the root folder if the file input is already set to `None`. It's super useful in AoiView where you always reset 3 FileInput when changing from 1 method to another. 
- Vastly speed up AoiView
- remove legacy prints
- add the loading state when method is being loaded
Fix #554
=> speed up aoi method change

CONTRIBUTING.rst, docs/source/tutorials/add-tile.rst, docs/source/tutorials/create_asset.rst, docs/source/tutorials/send-to-sepal.rst, docs/source/tutorials/structure.rst, docs/source/tutorials/translate-app.rst, docs/source/widgets/load_table.rst, sepal_ui/sepalwidgets/__init__.py, setup.py
the problem with Napoleon is now solved in sphinx 5.1.1 (https://github.com/sphinx-doc/sphinx/issues/10701#issuecomment-1196339819)
=> build: remove upper cap on sphinx

sepal_ui/mapping/__init__.py, sepal_ui/mapping/legend_control.py, sepal_ui/mapping/sepal_map.py, tests/test_LegendControl.py, tests/test_SepalMap.py
small implementation change: 
`Lengend` is now not a `Card` but a `WidgetControl`. It allows more flexibility to add it to the map: 
people that are used to ipyleaflet: 
```python 
legend = sm.LengendControl({})
map = SepalMap()
map.add_control(legend)
```
people that know the lib very well 
```python 
map = SepalMap()
map.add_legend({}, position="topleft")
```
I think the implementation you did pave the way for all the controls in general: 
- the ipyleaflet way (created outside used outside) 
- the semi auto (created with a specific method, added to the member)
- the lazy one (create at init state, added to the members)
This will of course be handled in another PR and another issue
=> Legend suggestion

docs/source/tutorials/create_asset.rst, sepal_ui/frontend/json/layer.json, sepal_ui/mapping/sepal_map.py, tests/test_SepalMap.py
As mentioned in #425, gee vector layers were not using the default style, with this PR, we will have this as a default behavior.
=> Set default style to vector layers in GEE

sepal_ui/frontend/css/custom.css
Fix #568 
The app bar as set with a higher z-inex to be on top of the fullscreen app, here I make sure that the drawer is even higher.
=> fix: set the drawer on top of the appbar

.pre-commit-config.yaml, docs/source/conf.py, sepal_ui/sepalwidgets/inputs.py
Fix #596 
I simply moved the `default_asset` addition into the `_get_items` method. 
I also trigger the full `_get_items` when the `default_asset` is changed
```python 
widget = sw.AssetSelect(default_asset=["users/bornToBeAlive/random300"])
widget
widget.default_asset = ["users/bornToBeAlive/random150"]
```
=> fix: keep default asset when reloading

docs/source/conf.py
=> docs: update icons

.pre-commit-config.yaml, docs/source/widgets/btn.rst, sepal_ui/reclassify/reclassify_view.py, sepal_ui/reclassify/table_view.py, sepal_ui/sepalwidgets/btn.py, sepal_ui/sepalwidgets/inputs.py, tests/test_Btn.py
Fix #594 
Multiple changes: 
- deprecate the "icon" and "text" keyword as they are boolean traits of the ipyvuetify Btn. It's still working as init parameter for the time being
- use "gliph" and "msg" instead 
- create traits for each one of them 
- observe these traints to update the content of the Btn
```python
toto = sw.Btn()
toto
```
```python
toto.msg = "tata"
toto
```
```python
toto.gliph = "fas fa-folder"
toto
```
=> fix: set icon and text as traits in btn

.github/workflows/unit.yml, setup.py
I wanted more information specifically: 
- the total execution time
- the error directly where they appear
- In github actions we still use the default one as it's a non interactive shell
=> test: use sugar-pytest to have more test outputs

sepal_ui/aoi/aoi_view.py, sepal_ui/mapping/draw_control.py
Fix #595
Create a aoi_dc on the fly if a map is specified. This create a duplicate but ensure that if 2 dcs are added to the map, AoiVeiw abject will only manipulate this one.
=> fix: create a specific aoi_dc on the map

.github/workflows/unit.yml, setup.py, tests/test_PlanetModel.py
Final touch to the pytest plugins: Fix #630 
- install `pytest-deadfixture` in `setup.py `
- use it the unit test suit against python 3.8 (example of failure: https://github.com/12rambau/sepal_ui/actions/runs/3571282698/jobs/6003017612)
- tune test_PlanetModel to expose the use of `cred` and `planet_api`
- install `pytest-cov` in `setup.py`
- use it in our unit test suit to generate the xml coverage file
=> test: add pytest missing plugins

sepal_ui/sepalwidgets/btn.py, tests/test_Btn.py
FIx #623 
- removed the default "click" parameter 
- remove the `left` trait of the `v_icon` when the text is not set
=> fix: remove left when only icon is set

docs/source/tutorials/add-tile.rst, docs/source/tutorials/custom-widget.rst, docs/source/widgets/btn.rst, sepal_ui/frontend/json/file_icons.json, sepal_ui/frontend/styles.py, sepal_ui/mapping/aoi_control.py, sepal_ui/mapping/fullscreen_control.py, sepal_ui/mapping/map_btn.py, sepal_ui/mapping/value_inspector.py, sepal_ui/reclassify/reclassify_view.py, sepal_ui/reclassify/table_view.py, sepal_ui/sepalwidgets/app.py, sepal_ui/sepalwidgets/btn.py, sepal_ui/sepalwidgets/inputs.py, sepal_ui/sepalwidgets/widget.py, sepal_ui/templates/map_app/component/tile/map_tile.py, sepal_ui/templates/panel_app/ui.ipynb, tests/test_Btn.py, tests/test_CopyToClip.py, tests/test_DownloadBtn.py, tests/test_DrawerItem.py, tests/test_FullScreenControl.py, tests/test_MapBtn.py, tests/test_MenuControl.py
- use fontawesome V6 
- change all the `fas` and `far` occurences by `fa-solid`(res. `fa-regular`)
- change the icons that were not free to their free alternative
**note**
`fas` will continue to work in v6 for quite some time so application will not need to change everything but their sizing is a bit different. 
Fix #576
=> Fontawesome V6

sepal_ui/sepalwidgets/alert.py, tests/test_Alert.py
- by default ùpdate_progress continues to refuse values >1 (no regression)
- the user can select a different `total` parameter for tqdm and then the value should only be <`total`
Fix #562
=> fix: update_progress accept values >1

sepal_ui/frontend/css/custom.css
=> fix: set dialog on top of everything

sepal_ui/translator/translator.py
Fix #648, Fix #654
- When a empty dict was set in the `Translator.sanitize` method, it was transformed into a list which was analysed as "non-empty" by the `Translator.delete_empty`. This is now solved and the translator behave as expected 
- reverse the logic of `Translator.merge_dict` for sementic reasons
- correct a mistake in my understanding of glob parsing, `.ipynb` file are tested back again
=> fix: translator issues

.github/workflows/unit.yml, .gitignore, noxfile.py, pyproject.toml, sepal_ui/bin/sepal_ipyvuetify.py
The build of v2.14.0 is blocked on conda-forge because the latest bin entry_point cannot work.
This PR add the appropiate tests and modify the name of the scripts to make it work.
=> fix: add checks for bin content 

pyproject.toml
It seems to be missing and the doc build fails because of it. My guess is that it was silentely included in one of the other libs and it has been removed recently
=> build: add nest_asyncio deps

sepal_ui/frontend/css/custom.css, sepal_ui/frontend/json/map_btn.json, sepal_ui/mapping/__init__.py, sepal_ui/mapping/map_btn.py, sepal_ui/mapping/sepal_map.py, sepal_ui/mapping/zoom_control.py, tests/test_ZoomControl.py
In the current implementation, the zoom control is a normal ipyleaflet widget so its display is kinda tricky: 
- transparent or not depending on the execution 
- use the voila background 
- don't respect theming 
- don't use the theme colors
This is a custom implementation of a python zooming widget. It is using the same look & feel as the other buttons (Vuetify material) and respect the themes. 
I think I cover all the potential situations.
=> add a custom zoomControl

.github/workflows/release.yml
when a new release is created the worklfow will:
- create a distrib 
- push it to pipy (which triggers conda-forge)
- push to the release branch
Fix #713
=> auto-merge main in release

noxfile.py, sepal_ui/aoi/aoi_model.py, sepal_ui/aoi/aoi_tile.py, sepal_ui/aoi/aoi_view.py
Fix #706 
As we now use the AOIView more often in custom map style application it became critical to modify the rendering of the AOI on the map natively. 
With this PR, the developer can change the AOI display directly when he creates the AOIView/Tile. as in the following example: 
```python
from sepal_ui import aoi 
aoi.AoiTile(map_style = {'opacity': 1, 'dashArray': '9', 'fillOpacity': 0.1, 'weight': 1})
```
=> make the aoi style customizable

sepal_ui/mapping/zoom_control.py
Fix #735
I've used the `data-xxx` html convention. more information can be found here: https://developer.mozilla.org/fr/docs/Learn/HTML/Howto/Use_data_attributes
=> fix: use attributes instead of _metadata

sepal_ui/aoi/aoi_view.py, sepal_ui/sepalwidgets/btn.py
Fix #732
The v_icon is init with an empty string so if no gliph is set up at launch, the _set_gliph method is never called. The trick is to init the gliph as a full empty gliph so that if nothing is called, it's hidden
=> fix: remove gliph when btn have only msg

sepal_ui/aoi/aoi_view.py, sepal_ui/sepalwidgets/btn.py, sepal_ui/sepalwidgets/inputs.py
Fix #730, Fix #746
The `layout_kwargs` was init to `{}` and then updated with `setdefaults` for all `DatePicker` without option. That's a mutable object rookie mistake, they were all sharing the same. I made it optional and if not present, it's inited in the `__init__` method. 
can be tested by running: 
```python 
toto = sw.DatePicker()
toto.v_model = "2022-06-15"
toto
```
or for the duplication issue: 
```python 
import sepal_ui.sepalwidgets as sw
class DateSelector(sw.Layout):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.w_unique_date = sw.DatePicker(label="Date")
self.w_ini_date = sw.DatePicker(label="Start date")
self.children = [
self.w_unique_date,
self.w_ini_date
]
date_selector = DateSelector()
date_selector …
```
=> fix: update datepicker

sepal_ui/mapping/__init__.py, sepal_ui/mapping/inspector_control.py, sepal_ui/mapping/sepal_map.py, sepal_ui/mapping/value_inspector.py, sepal_ui/message/en/inspector_control.json, tests/test_InspectorControl.py
Fix #731 
- Change the inspector rendering using a `tree_view`. It makes it easier to read data with many different bands/layers
- Change the name: We are more or less following a convention for the controls of the map: XXXControl. ValueInspector was the only one not respecting it. I renamed the class "InspectorControl" and created a "deprecated" one to avoid regression.
- complete messages: there was one key still hard coded in the .py file
=> refactor value inspector 

sepal_ui/sepalwidgets/alert.py
if you use an int total, the progress was closed on the second item (1) and reopen on the 3rd (2)
=> fix: close tqdm when total is reached

sepal_ui/mapping/inspector_control.py, tests/test_AoiView.py, tests/test_EELayer.py, tests/test_SepalMap.py
Fix #753 
add a simple marker where you click. useful when you start playing with the transparency of your layers. 
- add a marker layer when the control is created. it's hidden AND outside of the map
- show the control when the menu is opened 
- move the control to the clicked point
- hide (but keep the value) when the control is closed so that next time the marker will still be where the displayed data are still pointing
=> fix: add a marker on the map for inspection

sepal_ui/sepalwidgets/inputs.py, sepal_ui/sepalwidgets/sepalwidget.py, tests/conftest.py, tests/test_FileInput.py
Fix #769 
- FileInput now embed a `root` traits that is piloting how high you can go up in the hierarchy. 
- It can be set at init or while computing. 
- if the current `v_model` is higher, reload will make the parent node disapear, but you'll still be able to go deeper
```python 
from pathlib import Path
fi = sw.FileInput(root=Path.home())
fi
```
=> fix: add root parameters in FileInput

sepal_ui/sepalwidgets/inputs.py, tests/test_DatePicker.py
Fix #752
you can now create a dateipker set to today and/or dinamically change its date after initilization: 
```python 
sw.DatePicker().today()
dt = sw.DatePicker()
dt.today()
```
=> fix: add a today method to datepickers

noxfile.py
I decided to build the coverage as well when running the tests locally. Only they are build in HTML, longer to compute but it can be analysed in a normal browser.
=> fix: build the coverage analysis with nox as well

sepal_ui/planetapi/planet_model.py, tests/test_planetapi/test_PlanetModel.py, tests/test_planetapi/test_PlanetModel/test_get_mosaics.yml, tests/test_planetapi/test_PlanetModel/test_get_quad.yml
add 2 simple methods the retreive mosaics (`get_mosaics`) and single quad (`get_quad`) using the planet model.
The results are displayed as json dict so the developer can then do anything (download the thumbnail, the real image, display them on a map using the xyz server etc...)
Fix #803
=> fix: get_mosaics and get_quad in planetModel

.pre-commit-config.yaml, pyproject.toml, sepal_ui/scripts/utils.py
=> build: use anyascii instead of unidecode for licence compatibility

sepal_ui/mapping/layers_control.py
if the titles are too small, the width reduces to the bare minimum and it gets impossible to move the slider. In this PR I simply rollback to previous implementation: 
- height is free
- width is 400px whatever content
=> fix: freeze back layers_control width

sepal_ui/frontend/css/custom.css
By playing with the fullaplication map I relized we may overdid it by fixing the z-index of all theses components.
`Dialog` and `Menu` are 2 components that are added to the DOM by Javascript i.e. they are not just "under" their parent but somwhere else in the tree. Their positioning and z-index is therefore computed via JS. 
-  `Dialog` create a grey filler to avoid clicking outside at +1 z-index and a dialog div at +2 z-index
- `Menu` creates a div at +1 z-index from the activator
Initially we built these tricks to prevent issues when using the "real" fullscreen where menu and dialog were stuck behind the map. 
Now that the fullscreen mode is a css trick itself I think we should drop these css as it works well without it. 
**How did I noticed ?** 
I created a `Select` (which uses a …
=> fix: remove pin on dialog and menu z-index

sepal_ui/mapping/layers_control.py
Fix #818 
- set the listener first (to change both slider and checkbox if necessary)
- set the layer as pilot of the link so if layer visibility is set to False, it stays as it is. 
```python
from ipyleaflet import Map, basemaps, basemap_to_tiles
from sepal_ui import mapping as sm
m = sm.SepalMap(center=(52.204793, 360.121558), zoom=9)
dark_matter_layer = basemap_to_tiles(basemaps.CartoDB.Positron)
dark_matter_layer.visible = False
m.add_layer(dark_matter_layer)
m
```
=> fix: align the checkbox on the layer states

sepal_ui/sepalwidgets/inputs.py
Fix #824 
trim the inputs of assets. Some users are using manual copy/paste from documents, triming will help users and avoid meaningless errors. It doesn't seem to slow down the assetSelector too much.
=> fix: trim the asset input

sepal_ui/sepalwidgets/alert.py, sepal_ui/sepalwidgets/inputs.py
Fix #828 
As suggested by @dfguerrerom I moved from using the frontend only ipywidgets `jslink` to the traitlets `link`. 
Nothing specific to talk about it's straight forward. I think the planet errors are related to #825.
=> fix: replace jslink by link

docs/source/conf.py
by changing this context parameter, the `edit on github` link will point to the default branch
=> fix: change default branch on docs. closes #846

sepal_ui/message/en/decorator.json, sepal_ui/scripts/decorator.py, sepal_ui/sepalwidgets/alert.py, sepal_ui/sepalwidgets/app.py, sepal_ui/sepalwidgets/inputs.py, sepal_ui/sepalwidgets/sepalwidget.py, sepal_ui/sepalwidgets/tile.py, sepal_ui/sepalwidgets/widget.py, tests/test_planetapi/test_PlanetModel.py, tests/test_scripts/test_decorator.py, tests/test_sepalwidgets/test_Alert.py
Fix #852, Fix #851 
- fix the inconsistency between `catch_error` and `loading_button` by adding a `self` parameter to it. No need to specify the alert if the object have an `alert` member. 
- some typing refactoring
=> fix: add `self` to `catch_error` decorator

.github/workflows/release.yml, .github/workflows/unit.yml, pyproject.toml, sepal_ui/sepalwidgets/inputs.py, setup.py
It is no longer needed since python 3.7
=> build: finally drop setup.py

sepal_ui/sepalwidgets/inputs.py, tests/test_sepalwidgets/test_FileInput.py
closes #862 and a simple implementation of https://github.com/12rambau/sepal_ui/issues/864
- besides of fixing #862. I've implemented a simple `cache_dir` variable to improve the performance of the component.
=> fix: don't change folder when new folder is parent of root. 

sepal_ui/message/en/utils.json, sepal_ui/scripts/decorator.py, sepal_ui/scripts/utils.py
fix: #826 
Normally all the conection to GEE should be done using either the need_ee method or the need_ee decorator. So in both cases I decided to simply assert if at least one root exist. If not I raise an error. As this will be triggered before the widgets are displayed, it will be visible on the screen.
=> fix: display meaningfull message if the folder list is empty

sepal_ui/frontend/css/custom.css, sepal_ui/templates/map_app/ui.ipynb, sepal_ui/templates/panel_app/ui.ipynb
The message is manually placed at the top of the ui notebook in both template.
it uses the `loading-app` ID 
it's removed from the screen when loading of the widgets ends. 
Question: 
As we place apps in an overlay do we even need to extra CSS ? It seems to me that the markdown will simply go under it isn't it ?
=> fix: display a message at the top of the notebook while loading

.devcontainer/devcontainer.json
The devcontainer was using Python 3.12 which was leading to crash in fiona installation.
=> fix: use Python 3.11

tests/conftest.py, tests/test_aoi/test_AoiModel.py, tests/test_sepalwidgets/test_FileInput.py, tests/test_translator/test_Translator.py
=> refactor: use the pytest fixture for tmp directory

sepal_ui/message/en/locale.json, sepal_ui/planetapi/planet_model.py, sepal_ui/planetapi/planet_view.py, tests/test_planetapi/test_PlanetModel.py, tests/test_planetapi/test_PlanetView.py
- fixed #895 
- added method to load credentials from file
- add an option to store successful login credentials
To test:
```python
from sepal_ui.planetapi.planet_view import PlanetView
planet_view = PlanetView()
planet_view
```
=> Planet enhance

sepal_ui/aoi/aoi_model.py, sepal_ui/aoi/aoi_view.py, sepal_ui/message/en/locale.json, tests/test_aoi/test_AoiModel.py
- Related to #919.
- Basically I create a lazy import on the `gdf` when it is requested using a full GEE AoiModel.
- I also changed the `AoiView` method to add both local and ee layers independently.
=> feat: Make a lazy loading of gee gdf..close #919.

sepal_ui/sepalwidgets/inputs.py
this PR creates a new mutable class member `_initial_assets: list` which will be filled with a list of assets after the first instance creation of the `AssetSelect`. This member will be checked before running the `ee.data.listassets` call to earthengine, if the member has already data, the elements will use their data instead.
I also moved the decorator as I proposed in https://github.com/openforis/sepal_ui/issues/931
=> refactor: store initial assets in class variable

sepal_ui/scripts/gee.py
from the current recursive function implementation the time to load 100 assets stored in multiple folders, the time was:
####################### Recursive #######################
Execution time: 13.889884233474731 seconds
By using the suggested implementation we could improve the result  by 80%. 
####################### Async Concurrent 2 #######################
Execution time: 2.823052406311035 seconds
=> feat: draft async get assets

.github/workflows/release.yml, .github/workflows/unit.yml, .readthedocs.yaml, pyproject.toml
Aims to close #944 by removing the direct dependency and just installing the latest release.
Let's the tests see if it works.
=> ci: remove shpinx as direct dependency

sepal_ui/sepalwidgets/inputs.py
=> fix: closes #938

sepal_ui/mapping/sepal_map.py
- Add an optional `use_vis_params` to `add_layer` method in `SepalMap`. Sometimes layers come with a visualization that might be broken or dev doesn't want to display, it will be set True as default.
=> Add use_vis_params to add layer

sepal_ui/scripts/thread_controller.py, sepal_ui/sepalwidgets/inputs.py
- do the request of the assets in a separate thread
=> feat: request assets in a separate thread

pyproject.toml, sepal_ui/scripts/thread_controller.py, sepal_ui/sepalwidgets/inputs.py
When someone pastes an asset_id directly into the AssetSelect and then clicks a "button" which triggers an event, the AssetSelect validation doesn't get triggered until the button event finishes... this causes validations errors.
This PR adds an optional argument that:
- Triggers validation of AssetSelect with a debounce when the `update:search-input` event is emitted.
I don't foresee any issue with this change.
=> Asset select

tests/test_planetapi/test_PlanetModel/test_get_quad.yml
- It looks like planet will eventually change the previous download link... we don't have any implementation of this endpoint, we can just change the test data regression.
=> test: fix #957. change download response url

sepal_ui/mapping/draw_control.py
- Due to errors when using this tool, our tests should be more consistent with this tool.
=> fix: revert to legacy draw control due to errors
