sepal_ui/aoi.py
sepal_ui/mapping.py
sepal_ui/sepalwidgets.py

move from a packages to a object oriented definition of widgets

Proposal classes

---

sepal_ui/mapping.py

Raster inspector

---

sepal_ui/sepalwidgets.py

Make all file types by default

List all files by default

---

sepal_ui/sepalwidgets/inputs.py
sepal_ui/sepalwidgets/sepalwidget.py

I've tested this implementation in a few scenarios, not sure if it will work as a generic solution, what do you think?

apply visualization method to sepalwidgets

---

requirements.txt
sepal_ui/message/__init__.py
sepal_ui/message/en.json
sepal_ui/message/fr.json
sepal_ui/translator.py
setup.py

#71 
I created an object to automatically translate messages from json files (Daniel W. requirement)
in the `___init__.py` file of the `message` package, you'll find a demo implementation 
It can be used in all our modules on the plateform in the same way. 
I would like to push it to develop and create the test there

add translation capacity

---

sepal_ui/aoi/aoi_io.py
sepal_ui/aoi/tile_aoi.py
sepal_ui/scripts/run_aoi_selection.py
sepal_ui/sepalwidgets/inputs.py

- I display a different name that the asset Id (remove the manfest used by google 
- add the possiblity to reload the fileInput without changing folder 
- allow the user  to use a custom name when using shapefile and tables
- digest txt files in the table input 
- small typo and refactoring
_______
- I assume some tests will fail but I'll work on them in the develop branch

improve aoi selector 

---

sepal_ui/aoi/aoi_io.py
sepal_ui/aoi/tile_aoi.py
sepal_ui/message/__init__.py
sepal_ui/message/en.json
sepal_ui/message/es.json
sepal_ui/message/fr.json
sepal_ui/scripts/gee.py
sepal_ui/scripts/run_aoi_selection.py
sepal_ui/sepalwidgets/inputs.py
tests/test_Aoi_io.py
tests/test_TileAoi.py
tests/test_run_aoi_selection.py

- integrate the new aoi features
- translation tools
- several bug fix

new features

---

.travis.yml
README.rst

Codecov implementation

---

sepal_ui/sepalwidgets/inputs.py

Clean only if necessary

---

sepal_ui/reclassify/reclassify_view.py

Reclassify branch

---

sepal_ui/bin/module_deploy
sepal_ui/reclassify/parameters.py
sepal_ui/reclassify/reclassify_model.py
sepal_ui/reclassify/reclassify_tile.py
sepal_ui/reclassify/reclassify_view.py
sepal_ui/reclassify/table_view.py
sepal_ui/scripts/utils.py
sepal_ui/sepalwidgets/inputs.py

AssetSelect:
- Define `default_asset` parameter as trait in `SelectAsset` widget and have the chance to update the default assets once the widget is instantiated.
Switch decorator:
- Extend the behavior as mentioned in https://github.com/12rambau/sepal_ui/issues/263#issuecomment-912615658, It would be really nice if you can check it.

Improve AssetSelect and refactor Switch decorator

---

docs/source/conf.py
docs/source/widgets/about.rst
docs/source/widgets/alert.rst
docs/source/widgets/app.rst
docs/source/widgets/asset_select.rst
docs/source/widgets/btn.rst
docs/source/widgets/clip.rst
docs/source/widgets/date_picker.rst
docs/source/widgets/disclaimer.rst
docs/source/widgets/download_btn.rst
docs/source/widgets/file_input.rst
docs/source/widgets/index.rst
docs/source/widgets/load_table.rst
docs/source/widgets/markdown.rst
docs/source/widgets/number.rst
docs/source/widgets/password.rst
docs/source/widgets/sepal_widget.rst
docs/source/widgets/statebar.rst
docs/source/widgets/tile.rst
docs/source/widgets/tile_aoi.rst
docs/source/widgets/tile_reclassify.rst
docs/source/widgets/vector.rst
requirements.txt

It's preventing doc build in PR

build: remove sepal-ui from requirements.txt

---

sepal_ui/scripts/utils.py
tests/test_utils.py

Create a string followed by a consecutive underscore and number

Next string script

---

sepal_ui/sepalwidgets/sepalwidget.py

fix: prevent tooltip error when calling. closes #298

---

docs/source/modules/sepal_ui.scripts.rst
sepal_ui/scripts/utils.py
sepal_ui/scripts/warning.py
tests/test_utils.py

fix: display specific warnings in alerts

---

sepal_ui/message/en.json
sepal_ui/message/es.json
sepal_ui/message/fr.json
sepal_ui/sepalwidgets/inputs.py
tests/test_AssetSelect.py

- add the `types` trait
- update widget on `types` change 
- insure new `types` are legit types
- check asset type when using a custom one
- update docstring
- test new methods

Fix: improve AssetSelect

---

sepal_ui/bin/module_factory

update the readme in module_factory

---

setup.py

builds: add pre-commit to build

---

sepal_ui/sepalwidgets/inputs.py
tests/test_NumberField.py

Fix #333 
The test are passing, it's just GEE that think that I'm a malware (too many connection per minutes)

add increm in `NumberField`

---

sepal_ui/frontend/styles.py
sepal_ui/sepalwidgets/inputs.py

Fileselector

---

.pre-commit-config.yaml
setup.py

fix: only install pre-commit hooks once

---

.github/workflows/unit.yml

build: use codecov actions

---

.gitignore

Just to avoid syncing untitled files by mistake?

refactor: ignore untitled files

---

docs/source/tutorials/send-to-sepal.rst
sepal_ui/bin/module_deploy
sepal_ui/bin/module_factory
sepal_ui/bin/module_l10n
sepal_ui/bin/module_theme
sepal_ui/bin/module_venv
setup.py

- create a venv script 
- sanityse all the other script (because they were simply ugly)
- add docstring everywhere to allow the `--help` call
- update documentation

create a venv script to create and automatically link a ven to a kernel

---

sepal_ui/message/en/locale.json
sepal_ui/sepalwidgets/app.py

refactor: add translation keys for navdrawer items

---

CONTRIBUTING.rst

- Document env vars required to tests.

docs: document required env variables. related with #481

---

docs/source/modules/sepal_ui.sepalwidgets.Alert.rst
docs/source/modules/sepal_ui.sepalwidgets.Banner.rst
docs/source/modules/sepal_ui.sepalwidgets.DatePicker.rst
docs/source/tutorials/send-to-sepal.rst
docs/source/tutorials/structure.rst
sepal_ui/sepalwidgets/alert.py
tests/test_Alert.py

fix: remove bind method from Alert

---

.github/workflows/unit.yml
.gitignore
sepal_ui/reclassify/reclassify_view.py
sepal_ui/reclassify/table_view.py
sepal_ui/scripts/utils.py
sepal_ui/sepalwidgets/alert.py
sepal_ui/sepalwidgets/app.py
sepal_ui/sepalwidgets/sepalwidget.py
setup.py

Fix #499 
Ok it has taken me ages to fix the build error in GitHub actions. Sorry for the noise. 
Now, the warning in the documentation build will make the documentation fails. It will be useful to track down missing references in the API documentation

build: test the doc build for 3.8

---

docs/source/modules/sepal_ui.aoi.AoiModel.rst
sepal_ui/aoi/aoi_model.py
sepal_ui/mapping/sepal_map.py
sepal_ui/mapping/value_inspector.py
sepal_ui/sepalwidgets/tile.py
tests/test_Tile.py

everything is in the title
FIx #514 
Fix #511 
Fix #512

Fix small refactor issues

---

sepal_ui/message/en/utils.json
sepal_ui/scripts/utils.py
sepal_ui/sepalwidgets/alert.py
tests/test_Alert.py
tests/test_utils.py

refactor: move check_input to utils

---

sepal_ui/translator/translator.py
tests/test_Translator.py

it's working locally but the tests fail in the CD/CI

test: print file to identify what's wrong

---

sepal_ui/frontend/js/jupyter_embed.js
sepal_ui/frontend/js/jupyter_fullscreen.js
sepal_ui/mapping/__init__.py
sepal_ui/mapping/fullscreen_control.py
sepal_ui/mapping/menu_control.py
tests/test_MenuControl.py

add some functionalities for full map applications. 
Some iteration will be needed everywhere but that's a good start:
in short: 
- the map is now fullscreen or fullscreen - 48px so that we always see the header 
- I created a MenuCOntrol which is the "tiles" of the map
- It's by default design to work with Tile component 
starting point to solve #515

Full map app

---

sepal_ui/mapping/aoi_control.py
sepal_ui/mapping/menu_control.py
sepal_ui/mapping/value_inspector.py

I decided to use MenuControl as a base for both value_inspector and aoi_control 
Fix #515

use menuControl for the other widgets

---

docs/source/_static/switcher.json
sepal_ui/frontend/css/custom.css
sepal_ui/mapping/aoi_control.py
sepal_ui/mapping/menu_control.py
sepal_ui/mapping/value_inspector.py
sepal_ui/sepalwidgets/alert.py
tests/test_Alert.py
tests/test_MenuControl.py

fix small fries issues

---

sepal_ui/translator/translator.py
tests/test_Translator.py

- Make the search key method recursive.
- aims to close #572

fix: find forbiden keys recursivesly

---

sepal_ui/aoi/aoi_model.py
sepal_ui/aoi/aoi_view.py

This is a solution in order to close #589

fix: remove alert from aoi_model and add model as optional in aoi_view

---

sepal_ui/frontend/css/custom.css

This aims to close the issue #602 . Basically, it just increases the `.v-menu__content` zindex.

Fix z-index to menu content

---

sepal_ui/sepalwidgets/inputs.py
tests/test_DatePicker.py
tests/test_sepalwidgets.py

feat: improve date picker widget customization

---

tests/test_SepalMap.py

Everything is in the title, that's mainly a `maint` issue that @dfguerrerom was having on his local computer. 
Merging directly as I'm sure it works as expected

test: don't test localtileserver yet

---

.github/workflows/unit.yml

build: update actions version

---

sepal_ui/templates/map_app/.github/workflows/unit.yaml
sepal_ui/templates/panel_app/.github/workflows/unit.yaml

fix: base the linting on pre-commits

---

sepal_ui/mapping/aoi_control.py
sepal_ui/mapping/sepal_map.py
setup.py
tests/test_AoiControl.py
tests/test_SepalMap.py

fix: do not rely on harversine

---

README.rst

docs: add conda link

---

.pre-commit-config.yaml
sepal_ui/templates/map_app/module.yaml
sepal_ui/templates/panel_app/module.yaml

fix: add a modue.yaml file

---

sepal_ui/aoi/aoi_model.py
sepal_ui/scripts/decorator.py
sepal_ui/scripts/utils.py
tests/test_AoiModel.py

refactor: drop the gee reading to get the bounds

---

sepal_ui/sepalwidgets/tile.py

simplify TileAboute

---

sepal_ui/frontend/resize_trigger.py

It was only because didn't read the js file.

fix: read resize_trigger js as text. Closes #709

---

sepal_ui/planetapi/planet_model.py

fix: drop deprecated scenes

---

.pre-commit-config.yaml
pyproject.toml

refactor: remove isort parameters

---

sepal_ui/aoi/aoi_model.py

fix: change aoi color to primary

---

sepal_ui/sepalwidgets/sepalwidget.py
tests/test_SepalWidget.py

fix: make get_children always recursive

---

pyproject.toml

Fix #734
need to be tested in the next fix release

fix: update package discovery

---

sepal_ui/templates/map_app/map_ui.ipynb
sepal_ui/templates/panel_app/no_ui.ipynb

fix: load autoreload extension before using it

---

sepal_ui/frontend/json/file_icons.json

fix: remove last fa5 icon

---

CONTRIBUTING.rst

I'm not fully sure if the command you posted has to install the local package "." or just install the `PyPI` "sepal_ui", would you mind confirming me?

docs: editable mode

---

sepal_ui/sepalwidgets/sepalwidget.py

Fix #763
@dfguerrerom  let me know if this solves your issue, the code you show worked on my side in all the tested configurations
once it's merged I'll release a patch on pypi

fix: add html to the tested widgets

---

sepal_ui/scripts/decorator.py
sepal_ui/sepalwidgets/app.py
tests/test_aoi/test_AoiModel.py
tests/test_mapping/test_InspectorControl.py
tests/test_sepalwidgets/test_VectorField.py

- fix building error related to D212 changes 
- use GADM 4.1 instead of 3.6 Fix #779

docs: fix building errors

---

.github/workflows/unit.yml
.readthedocs.yaml
docs/source/conf.py
noxfile.py
pyproject.toml
sepal_ui/aoi/aoi_view.py

related to #783 and #759 
it's just a patch it will need to be removed once the corresponding PR are merged

refactor: use patched versions of sphinx and deprecated

---

docs/source/conf.py
sepal_ui/mapping/__init__.py
sepal_ui/mapping/layers_control.py
sepal_ui/mapping/marker_cluster.py
tests/test_mapping/test_MarkerCluster.py

I simply linked the visible traits to all underlying markers
Fix #798 
also Fix #801 by accident

fix: add a custom MarkerCluster

---

sepal_ui/templates/map_app/noxfile.py
sepal_ui/templates/panel_app/noxfile.py

create a nox session to launch app in notebooks

---

.readthedocs.yaml

build: refactor rdt build environment

---

.github/workflows/unit.yml
sepal_ui/templates/map_app/.github/workflows/unit.yaml
sepal_ui/templates/panel_app/.github/workflows/unit.yaml

test: reorder tests in matrix

---

tests/test_planetapi/test_PlanetModel.py
tests/test_planetapi/test_PlanetModel/test_get_mosaics.yml
tests/test_planetapi/test_PlanetModel/test_get_quad.yml

fix the planet test as I recently updated the API key (it changes the id of the produced responses)

test: regen planet files

---

sepal_ui/sepalwidgets/alert.py
tests/test_sepalwidgets/test_Alert.py

fix: only use tqdm parameters after reset

---

.github/workflows/unit.yml
.readthedocs.yaml
noxfile.py

fix: use deprecated from tantale

---

sepal_ui/scripts/gee.py
tests/conftest.py
tests/test_mapping/test_SepalMap.py
tests/test_scripts/test_gee.py

fix: add method to delete a folder and all its content

---

docs/source/conf.py

docs(conf): update default branch name

---

tests/test_planetapi/test_PlanetModel/test_get_mosaics.yml

fix: update planet mosaic list in tests

---

sepal_ui/templates/map_app/ui.ipynb
sepal_ui/templates/panel_app/no_ui.ipynb
sepal_ui/templates/panel_app/ui.ipynb

refactor: use double quote for the run command

---

.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

this devcontainer will be used when creating a codespace from this repository. it ensure nox and pre-commit are always installed and pre-commit hooks are activated. 
No excuses for mistakes !

build: create a devcontainer

---

pyproject.toml

same bug as in all pydata-sphinx-theme dependant documentation

fix: use sphinx<7 for the moment

---

.github/workflows/unit.yml
noxfile.py

Fix #874 
everything is in the title

use noxfile for github test

---

docs/source/_static/switcher.json
docs/source/conf.py

I added 4 extra versions and rewired stable to latest. Also I set up the version warning banner that will be displayed on top of version that are not the stable one.
Fix #881

docs: improve version swithcer 

---

docs/source/_static/css/custom.css
docs/source/conf.py

fix: stop overriding the default behavior of the footer

---

sepal_ui/frontend/js/fontawesome.js

- It will fix the red print error when we were loading the app

fix: fix js code issues on fontawesome removing code

---

pyproject.toml
sepal_ui/message/en/locale.json
sepal_ui/scripts/utils.py
sepal_ui/sepalwidgets/app.py
sepal_ui/templates/panel_app/CHANGELOG.md
sepal_ui/templates/panel_app/pyproject.toml
tests/conftest.py
tests/test_scripts/test_utils.py
tests/test_sepalwidgets/test_App.py

related to #885 
- This PR creates a version card element that will be appended to the bottom of the `NavigationDrawer`.
- It will assume there's a `__version__.py` file in the root folder containing the current version
- It will assume the latest version of the module is in `release` branch
- If there's a release, it will use the text generated there as initial element, if not, only the changelog will be displayed.
[screen-capture.webm](https://github.com/12rambau/sepal_ui/assets/12363250/f17c1864-a7cf-414c-a397-2999d0e2f63a)
- I need to create the tests...
- But in the meantime, what do you think about this?

Version card

---

sepal_ui/message/ar-SA/decorator.json
sepal_ui/message/ar-SA/locale.json
sepal_ui/message/ar-SA/utils.json
sepal_ui/message/es/decorator.json
sepal_ui/message/es/locale.json
sepal_ui/message/es/utils.json
sepal_ui/message/fr/decorator.json
sepal_ui/message/fr/locale.json
sepal_ui/message/fr/utils.json
sepal_ui/message/pt-PT/decorator.json
sepal_ui/message/pt-PT/locale.json
sepal_ui/message/pt-PT/utils.json
sepal_ui/message/ru-RU/decorator.json
sepal_ui/message/ru-RU/locale.json
sepal_ui/message/ru-RU/utils.json
sepal_ui/message/zh-CN/decorator.json
sepal_ui/message/zh-CN/locale.json
sepal_ui/message/zh-CN/utils.json

Revert "New Crowdin updates"

---

pyproject.toml

I have unpinned the planet version and now it works on my local dev env.
Let the tests run.
- Issues:
- close https://github.com/openforis/sepal_ui/issues/936
- close https://github.com/openforis/sepal_ui/issues/920

fix(planet.ver): unpin planet version

---

.github/workflows/unit.yml
pyproject.toml

build: drop support for python 3.8. closes#942

---

sepal_ui/frontend/css/custom.css

- For some reason the bug came again... voila updated something

fix: https://github.com/openforis/sepal_ui/issues/893

---

pyproject.toml
sepal_ui/mapping/draw_control.py

feat: add geoman drawing control
